spring.application.name=hikeway
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/hikeway-keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/hikeway-keycloak/protocol/openid-connect/certs
