spring.application.name=hikeway
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/hikeway-keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/hikeway-keycloak/protocol/openid-connect/certs
keycloak.server-url=http://localhost:8081
keycloak.realm=master
keycloak.target-realm=hikeway-keycloak
keycloak.client-id=admin-cli
keycloak.username=admin
keycloak.password=1234

spring.datasource.url=jdbc:postgresql://localhost:5432/hikewaydb
spring.datasource.username=hikeway
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect